# Generated by Django 4.0.5 on 2022-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
