# Generated by Django 4.0.5 on 2022-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_gamesession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Slug'),
        ),
    ]
